### ISSUE TITLE
Bill Text missing XML's

### ISSUE THREAD

**Issue by acmcneal** [usgpo/bulk-data#91]
Starting on 9/4 several bill text files on congress.gov are missing XML's - will XML versions be added?

**Comment by jonquandt** [comment]
Good afternoon -- if you could provide a list of the ones that you see as missing XML files, we can look into it.

**Comment by acmcneal** [comment]
there are over 300 - most bills since 9/4. For example HR5186

**Comment by jonquandt** [comment]
It seems that there may be an issue on the congress.gov side. I will reach out to them to investigate. 

I see that HR5186 is available via the govinfo bulkdata repository here:
https://www.govinfo.gov/bulkdata/BILLS/117/1/hr/BILLS-117hr5186ih.xml

Also via our API:
https://api.govinfo.gov/packages/BILLS-117hr5186ih/summary?api_key=DEMO_KEY
https://api.govinfo.gov/packages/BILLS-117hr5186ih/xml?api_key=DEMO_KEY

https://api.govinfo.gov/collections/BILLS/2021-09-04T00:00:00Z?offset=0&pageSize=100&api_key=DEMO_KEY

**Comment by acmcneal** [comment]
It looks like the issue was resolved and XMLs are being delivered as of Saturday morning - none of been backfilled at this point though, is congress.gov planning to backfill the missing text starting from 9/4?

**Comment by cmenard9** [comment]
There are still missing XMLs particularly HR3239, HR3241, HR5677, HR5679, HR5705, HR5718,

**Comment by llaplant** [comment]
@cmenard9, 

H.R. 3239, H.R. 3241, H.R. 5677, H.R. 5679, H.R. 5695, and H.R. 5705 are codification measures, and due to the drafting process, XML is not available for codification measures.

H.R. 5718 IH is also not available in XML.

More information about data anomalies is available at https://www.congress.gov/help/data-anomalies.

**Comment by llaplant** [comment]
Closing but can re-open if needed.
